# Generated by Django 5.0.1 on 2024-03-10 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="заголовок")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="подзаголовок",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время добавления"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SCIENCE", "Наука"),
                            ("MUSIC", "Музыка"),
                            ("CINEMA", "Кинематограф"),
                            ("OTHER", "Другое"),
                        ],
                        default="OTHER",
                        max_length=128,
                        verbose_name="категория",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, upload_to="pictures/", verbose_name="изображение"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
                "ordering": ("-created_at",),
            },
        ),
    ]
