# Generated by Django 5.0.1 on 2024-03-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(default=123, verbose_name="тело поста"),
            preserve_default=False,
        ),
    ]
