# Generated by Django 5.0.1 on 2024-03-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("science", "Наука"),
                    ("music", "Музыка"),
                    ("cinema", "Кинематограф"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=128,
                verbose_name="категория",
            ),
        ),
    ]
