# Generated by Django 5.0.1 on 2024-03-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=128, verbose_name="полное имя"),
                ),
                ("email", models.EmailField(max_length=128, verbose_name="почта")),
                ("message", models.TextField(verbose_name="сообщение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время отправки"
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
                "ordering": ("-created_at",),
            },
        ),
    ]
